# Validating Admission Policy
# Name: Prevent ConfigMap security vulnerability (CVE-2021-25742)
# Docs: https://hub.datree.io/built-in-rules/prevent-configmap-security-vulnerability-cve-2021-25742
# Severity: High

apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: "vap-cve-001-prevent-containers-from-accessing-host-files-by-using-high-uids"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["configmaps"]
  validations:
    - expression: (object.kind == "ConfigMap" && ((object.metadata.name in ["nginx-config", "nginx-conf", "ingress-nginx-controller"] && "name" in object.metadata) || (object.metadata.namespace in ["ingress-nginx", "nginx-ingress"] && "namespace" in object.metadata))) && ("data" in object && "allow-snippet-annotations" in object.data && object.data['allow-snippet-annotations'] == true)
      message: "Missing property object `allow-snippet-annotations` - set it to 'false' to override default behaviour (see more at https://hub.datree.io/built-in-rules/prevent-configmap-security-vulnerability-cve-2021-25742)"
